### ISSUE TITLE
Can we make something similar for skipping censored scenes from a video?

### ISSUE THREAD

**Issue by picwellwisher12pk** [michaelbull/vlc-credit-skipper#1]
Hi there, I have been trying to learn about VLC development. Not sure how much I need to know to make a extension for vlc. I had an idea to make a extension that can skip all the censored scenes from a movie, so one can see it with family and children.  Can we work together on it?

**Comment by mk-pmb** [comment]
The core magic happens in the `table.insert(options, …` commands. The function holding them replaces all playlist entries with new entries that are basically the same, except for special options `start-time` and `stop-time`. If you have a list of all the uncensored parts (maybe you can guess them from subtitles or similar), you could add a playlist entry for each uncensored part.
