### ISSUE TITLE
how could this be used in convert mode

### ISSUE THREAD

**Issue by bobombolo** [michaelbull/vlc-credit-skipper#2]
and in particular how to use this in batch conversions?

**Comment by michaelbull** [comment]
What is convert mode? This script doesn't convert anything, it enqueues a playlist with the start/end times of every item modified to exclude the start/end credits. The source files remain unmodified.

**Comment by bobombolo** [comment]
when you use VLC player's convert/save mode where you re-encode the file.
https://www.vlchelp.com/convert-video-format/
and in batch mode from the command line:
https://wiki.videolan.org/VLC_HowTo/Transcode_multiple_videos/

**Comment by michaelbull** [comment]
Can you explain what you expect this plugin to do with regards to the convert mode?

**Comment by bobombolo** [comment]
i guess this is the answer to the latter portion, about cli, https://stackoverflow.com/questions/29047899/run-vlc-extension-from-command-line#29049184
some digging revealed the advanced command line options --start-time and --stop-time

**Comment by bobombolo** [comment]
oh, sorry, i was hoping that the plugin could add a tab in the convert mode for trimming the start or end off. it would be nice to be able to use the same profiles that we create in the normal use of the plugin.

**Comment by bobombolo** [comment]
![screenshot from 2018-03-27 15-47-14](https://user-images.githubusercontent.com/25610408/37991219-a0e02db4-31d6-11e8-9f94-542e702807d7.png)
![screenshot from 2018-03-27 15-47-27](https://user-images.githubusercontent.com/25610408/37991220-a0faddd0-31d6-11e8-958d-f4b661a6d630.png)

**Comment by bobombolo** [comment]
![screenshot from 2018-03-27 16-04-11](https://user-images.githubusercontent.com/25610408/37991997-9bd41fd6-31d8-11e8-91fe-1073af2ad7e0.png)
this is "convert mode"
